#server:
#    port: 8080

#spring:
#    dubbo:
#        application:
#            name: boot-dubbo-provider
#        registry:
#            address: zookeeper://192.168.102.45:2181
#        protocol:
#            name: dubbo
#            port: 20880
#        scan:
#            com.home.alibaba.dubbo.provider.service

consumer.dubbo.port = 8080
provider.dubbo.port = 8081